repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: julia-format
        name: JuliaFormatter
        entry: julia --startup-file=no --project=build_tools build_tools/format.jl --check
        language: system
        files: '(\.jl$|^\.JuliaFormatter\.toml$|^build_tools/Project\.toml$)'
        pass_filenames: false
